services:
  front:
    build: ./front
    ports:
      - "8501:8501"
    volumes:
      - ./front/src:/app/src
    
  back:
    build: back/
    ports:
      - "8000:8000"
    volumes:
      - ./back/src:/app/src
 