services:
  front:
    build: ./front
    ports:
      - "8080:80"
    volumes:
      - ./front/src:/app/src

  back:
    build: back/
    ports:
      - "8000:8000"
    volumes:
      - ./back/src:/app/src
